# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest


steps:

# - task: DownloadSecureFile@1
#   name: pemkey
#   displayName: 'Download CA certificate'
#   inputs:
#     secureFile: 'dotnet-app_key.pem'
# - script: |
#     cat $(pemkey.secureFilePath)
#     chmod 400 $(pemkey.secureFilePath)

- task: SSH@0
  inputs:
    sshEndpoint: 'bastin'
    runOptions: 'inline'
    inline: 'ssh -i key.pem azureuser@10.0.0.5 ls -ltr'
    readyTimeout: '20000'